imputaciones_imputaciones_homepage:
    path:     /
    defaults: { _controller: ImputacionesImputacionesBundle:Imputaciones:index }


imputaciones_imputaciones_diario:
    path:     /diario
    defaults: { _controller: ImputacionesImputacionesBundle:Imputaciones:diario }
