parameters:
#    imputaciones_imputaciones.example.class: Imputaciones\ImputacionesBundle\Example

services:
#    imputaciones_imputaciones.example:
#        class: %imputaciones_imputaciones.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
